/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerBugRouteImport } from './routes/worker-bug'
import { Route as IndexRouteImport } from './routes/index'

const WorkerBugRoute = WorkerBugRouteImport.update({
  id: '/worker-bug',
  path: '/worker-bug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/worker-bug': typeof WorkerBugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/worker-bug': typeof WorkerBugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/worker-bug': typeof WorkerBugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/worker-bug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/worker-bug'
  id: '__root__' | '/' | '/worker-bug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkerBugRoute: typeof WorkerBugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker-bug': {
      id: '/worker-bug'
      path: '/worker-bug'
      fullPath: '/worker-bug'
      preLoaderRoute: typeof WorkerBugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkerBugRoute: WorkerBugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
